name = "SeismicDatabaseManager"
uuid = "84372de5-a21e-444f-9e32-3247706d4e35"
version = "0.1.0"
authors = ["Chang Guo <changguo1998@gmail.com"]

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LengthAreaVolume = "efc29244-82b9-40dc-80c2-83e112b54aab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SeisTools = "1a3a5297-0f7d-450c-8955-231a439346a8"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[sources]
LengthAreaVolume = {rev = "master", url = "https://gitee.com/changguo1998/LengthAreaVolume.jl"}
SeisTools = {rev = "develop", url = "https://gitee.com/changguo1998/SeisTools.jl"}

[compat]
CodecZlib = "0.7.8"
DelimitedFiles = "1.9.1"
Downloads = "1.6.0"
LengthAreaVolume = "0.1.0"
Mmap = "1.11.0"
Printf = "1.11.0"
SeisTools = "0.2.2"
TOML = "1.0.3"
Tar = "1.10.0"
ZipFile = "0.10.1"
